version: "3.7"
services:

  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: tweety2
    container_name: tweety2-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - bridge
  db:
    image: mysql:5.7
    container_name: tweety-db
    ports: 
      - 3333:3306
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: root
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - bridge

  nginx:
    image: nginx:1.17-alpine
    container_name: tweety-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
    networks:
      - bridge
  

networks:
  app:
    driver: bridge